
// Informative casus belli names and relative type
// Extracted from game file "common/cb_types/00_cb_types.txt"

define({
    cb_annex: "annex_country",
    cb_border_war: "take_border",
    cb_change_government: "war_goal_change_government",
    cb_claim_throne: "take_capital_throne",
    cb_colonial: "take_colony",
    cb_colonial_independance_war: "defend_capital_independ",
    cb_conquest: "take_claim",
    cb_core: "take_core",
    cb_crusade: "superiority_crusade",
    cb_daimyo_annex: "annex_country",
    cb_defection: "take_core_defection",
    cb_defender_of_the_faith: "defend_country_faith",
    cb_dishonored_call: "superiority_insult",
    cb_disloyal_vassal: "take_capital_disloyal",
    cb_excommunication: "take_province_excommunication",
    cb_fabricated_claims: "take_capital_fabricated_claims",
    cb_heretic: "superiority_heretic",
    cb_horde_vs_civ: "superiority_horde",
    cb_hre_attacked: "take_province_hre",
    cb_humiliate: "humiliate",
    cb_imperial: "take_capital_imperial",
    cb_imperial_ban: "take_province_ban",
    cb_independence_war: "defend_capital_independence",
    cb_independent_daimyo_annex: "annex_country",
    cb_insult: "superiority_insult_mutual",
    cb_liberation: "take_capital_liberation",
    cb_loan_cancelled: "superiority_loan",
    cb_nationalist: "take_province_nationalist",
    cb_overseas: "superiority_primitives",
    cb_primitives: "superiority_primitives",
    cb_religious_conformance: "take_capital_conformance",
    cb_religious_liberation: "take_province_religion",
    cb_restore_personal_union: "take_capital_personal_unio",
    cb_revoke_electorate: "revoke_elector",
    cb_revolutionary: "war_goal_change_government_mutual",
    cb_shogun_annex: "annex_country",
    cb_spy_discovered: "superiority_spy",
    cb_super_badboy: "take_capital_punitive",
    cb_trade_war: "superiority_trade_mutual",
    cb_trade_war_triggered: "superiority_trade",
    cb_tribal_feud: "take_province_tribal_feud",
    cb_vassalize_mission: "take_capital_vassalize"
});
